version: '3.9'

services:
  news-aggregator:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_NEWS_API_KEY=${VITE_NEWS_API_KEY}
        - VITE_GUARDIAN_API_KEY=${VITE_GUARDIAN_API_KEY}
        - VITE_NEW_YORK_TIMES_API_KEY=${VITE_NEW_YORK_TIMES_API_KEY}
    container_name: news-aggregator
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
